import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Banner from './components/Banner/Banner'
import Navbar from './components/Navbar/Navbar'
import { ThemeProvider } from './context/ThemeContext'
import StyledComponentsRegistry from './lib/registry'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout ({ children }: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <StyledComponentsRegistry>
            <Navbar />
            <Banner />
            {children}
          </StyledComponentsRegistry>
        </ThemeProvider>
      </body>
    </html>
  )
}
